# SMTP pour l’alerte e-mail via Gmail
SMTP_HOST       = "smtp.gmail.com"
SMTP_PORT       = 587
SMTP_USER       = "zhassaine05@gmail.com"
SMTP_PASSWORD   = "ggux ingm smmo bzyc"
ALERT_TO_EMAIL  = "zhassaine05@gmail.com"

# Clé OpenAI
OPENAI_API_KEY = "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"

